version: "3.8"

services:
  backend:
    build: ./calculator_project
    volumes:
      - ./calculator_project:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1

  frontend:
    build: ./calculator_frontend
    volumes:
      - ./calculator_frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
